# GenNN-InverseMicro: VAE Configuration File for training

model_params:
  input_channels: 1
  latent_dim: 12
  # hidden_dims: [32, 64, 128, 256]
  input_size: 28

training_params:
  batch_size: 64
  epochs: 100
  learning_rate: 0.001
  beta: 0.001  # Beta-VAE weight
  device: "cpu" # or "cpu"

pth_path: "models/vae/best_vae.pth"