# GenNN-InverseMicro: VAE Configuration File for training

model_params:
  input_channels: 3
  latent_dim: 12
  hidden_dims: [32, 64, 128]
  input_size: 96

training_params:
  batch_size: 8
  epochs: 5
  learning_rate: 0.0001
  beta: 0.0001  # Beta-VAE weight
  device: "cuda" # or "cpu"

pth_path: "models/vae/best_vae.pth"